spring.application.name=payment-service



server.port=8092

spring.datasource.url=jdbc:mysql://localhost:3306/paymentservicedatabase?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

razorpay.key.id=rzp_test_SfKTok9JGsSB7U
razorpay.key.secret=BaAd1wiHwiTA0AfgWbLPNIFR



springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html



swagger.server.url=http://localhost:8080/api/payment